#!/usr/bin/env bash
#
# Generate the plugin's derived build files from the CLI's package metadata.
#
# `requirements.txt` and `VERSION` are build artifacts that happen to be
# committed: the plugin is installed by copying this repo's root into a
# versioned cache, with no uv and no lockfile resolution at install time, so
# `bin/costcompass` needs a flat hash-pinned dependency list sitting next to it.
# `plugin.json`'s version is the same number wearing a marketplace hat.
# `pyproject.toml` is the one place a version is authored. Edit it (or
# `uv.lock`) and re-run this script. Never hand-edit `requirements.txt`,
# `VERSION`, or `plugin.json`'s version field.
#
#   gen-build-files.sh            regenerate
#   gen-build-files.sh --check    fail if stale (used by run-tests.sh)
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

command -v uv >/dev/null || { echo "gen-build-files: uv is required" >&2; exit 1; }

# Build into a staging tree, then either diff it or move it into place. Staging
# keeps --check honest: it compares against a freshly generated copy rather than
# trusting whatever is already committed.
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# Dependencies, hash-pinned from the lockfile the CLI is tested against. The
# project itself is excluded; the wrapper installs it from the repo root.
#
# Redirect rather than `-o`: uv records its own argv in the file header, so an
# output path would embed this run's temp directory and the --check diff would
# report drift on every invocation.
#
# NO_COLOR for the same reason, one step further: uv colorizes the `# via ...`
# provenance comments when it believes the caller wants color, and the redirect
# is not enough to stop it — FORCE_COLOR overrides the not-a-TTY check, and some
# agent and CI runners set it globally. The escapes then land in the generated
# file, so --check compares a clean committed file against a colorized fresh one
# and reports drift that regenerating cannot fix; it only writes the escapes
# into the repo. It has to be the environment variable rather than the
# equivalent `--color never` flag, because that flag would join the recorded
# argv above and change the header on every line of this file.
( cd "$ROOT" && NO_COLOR=1 FORCE_COLOR= uv export \
    --format requirements-txt \
    --no-dev \
    --no-emit-project \
    --quiet \
    > "$STAGE/requirements.txt" )

# Version stamps, both tracking pyproject.toml:
#
#   VERSION      — what the wrapper reports while bootstrapping. Its venv is
#                  keyed on a digest of the actual code, not on this string, so
#                  a stale VERSION is cosmetic rather than a correctness bug —
#                  but it is still the number a user sees.
#   plugin.json  — what the marketplace installs under, so a stale one is worse
#                  than cosmetic: it names the cache directory, and a bump that
#                  missed it would ship new code at the old version.
#
# plugin.json is hand-authored apart from this one field, so substitute in place
# rather than re-serializing — a json round-trip would reformat the whole file
# and turn every future hand edit into a diff against this script's taste.
uv run --quiet --project "$ROOT" python -c "
import pathlib, re, tomllib
root = pathlib.Path('$ROOT')
stage = pathlib.Path('$STAGE')
version = tomllib.loads((root / 'pyproject.toml').read_text())['project']['version']

stage.joinpath('VERSION').write_text(version + '\n')

manifest = (root / '.claude-plugin/plugin.json').read_text()
stamped, n = re.subn(r'(\"version\"\s*:\s*)\"[^\"]*\"', r'\g<1>\"%s\"' % version, manifest, count=1)
if n != 1:
    raise SystemExit('gen-build-files: no \"version\" field found in .claude-plugin/plugin.json')
stage.joinpath('plugin.json').write_text(stamped)
"

# The commit the shipped code was generated from, for `costcompass --version`.
#
# It has to be stamped into a file because it cannot be recovered at runtime:
# the plugin is installed by copying this repo into a versioned cache that
# carries no `.git`, and the CLI is then installed into a venv, so the imported
# package cannot reach a checkout relative to its own __file__ either.
#
# Empty outside a git tree — building from an unpacked sdist should degrade to
# printing just the version, not fail.
SHA="$(git -C "$ROOT" rev-parse --short=12 HEAD 2>/dev/null || true)"
cat > "$STAGE/githash.py" <<EOF
"""Generated by scripts/gen-build-files.sh — do not hand-edit.

Empty when generated outside a git tree.
"""

GIT_SHA = "$SHA"
EOF

# Staged name -> path in the repo.
GENERATED=(
    "requirements.txt:requirements.txt"
    "VERSION:VERSION"
    "plugin.json:.claude-plugin/plugin.json"
    "githash.py:src/costcompass/githash.py"
)

# githash.py is deliberately not compared against the freshly generated copy,
# and that is not an oversight to tidy up later: a file recording HEAD cannot
# live inside the commit that HEAD names. The moment the commit carrying it
# lands, HEAD has moved and the stamped value is one commit behind by
# construction — an equality check would then fail on every subsequent commit,
# and regenerating could never settle it.
#
# What is worth asserting is that the file exists and holds something the CLI
# can read, and — when there is a git tree to have read a sha from — that the
# value is not empty, which is how a silently failing generator would present.
# Accuracy beyond that comes from where the value is written rather than from a
# diff: release.sh regenerates from a clean tree on main immediately before
# committing and then asserts the stamp equals HEAD, so a published sha does
# name the commit whose src/ ships.
#
# Deliberately NOT checked: that the sha resolves to a reachable commit
# (`git cat-file -e`). It would false-fail on a shallow clone, where the stamped
# commit is simply outside the truncated history, and after any rebase or amend
# that orphans it — turning a diagnostic aid into a broken build on trees that
# are fine.
CHECK_EXACT=("requirements.txt" "VERSION" "plugin.json")

# Empty is legitimate outside a git tree (sdist), so the stricter pattern only
# applies when this run could see a repository.
SHA_PATTERN='^GIT_SHA = "[0-9a-f]*"$'
[[ -n "$SHA" ]] && SHA_PATTERN='^GIT_SHA = "[0-9a-f]+"$'

if [[ $CHECK -eq 1 ]]; then
    status=0
    for entry in "${GENERATED[@]}"; do
        name="${entry%%:*}"
        path="$ROOT/${entry#*:}"
        case " ${CHECK_EXACT[*]} " in
            *" $name "*)
                diff -q "$STAGE/$name" "$path" >/dev/null 2>&1 || status=1 ;;
            *)
                grep -Eq "$SHA_PATTERN" "$path" 2>/dev/null || status=1 ;;
        esac
    done
    if [[ $status -ne 0 ]]; then
        echo "gen-build-files: derived files are stale — they have drifted from pyproject.toml/uv.lock." >&2
        echo "                 Run: scripts/gen-build-files.sh" >&2
        exit 1
    fi
    echo "gen-build-files: requirements.txt, VERSION, plugin.json and githash.py are in sync"
    exit 0
fi

for entry in "${GENERATED[@]}"; do
    cp "$STAGE/${entry%%:*}" "$ROOT/${entry#*:}"
done

echo "gen-build-files: regenerated $(tr -d '\n' < "$ROOT/VERSION") (git ${SHA:-unknown})"
